<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email address_email_create</name>
   <tag></tag>
   <elementGuidId>651ac1a1-a6b5-4ba8-9c55-29e978d48c94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#email_create</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='email_create']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60e5dee8-6f43-414d-9e64-2db3911c598d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>566d5fe4-b2b6-4a6f-bf0c-f5ff7ae91aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>is_required validate account_input form-control</value>
      <webElementGuid>c14d0f7d-6474-4d4b-9921-d616eff3c2b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>isEmail</value>
      <webElementGuid>642b404b-fc85-4468-a6f5-2069fe41b889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email_create</value>
      <webElementGuid>94c2c1ba-2c48-4f74-8a21-b38a2bed92f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email_create</value>
      <webElementGuid>4f2f18f1-e1d1-4bed-b378-4a1b7951d6e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email_create&quot;)</value>
      <webElementGuid>110e6a13-ba07-4de9-8fba-08648030f9fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='email_create']</value>
      <webElementGuid>6ef1ce8e-3a44-4ca7-85a3-d173c0f0bc6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='create-account_form']/div/div[2]/input</value>
      <webElementGuid>267fbd9c-7e91-4ecc-bfe2-dab1940c1706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>146bb850-fbb6-4d10-aee3-14afe32322fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'email_create' and @name = 'email_create']</value>
      <webElementGuid>f65ac841-cde0-4542-a139-d781f5a8dfc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
