<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Buzz</name>
   <tag></tag>
   <elementGuidId>2ef1a231-1e09-4f0f-91a6-238d3fd91b76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_buzz_viewBuzz']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu_buzz_viewBuzz</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>53f0bcb2-51d4-4cff-88a2-c15d40e230e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/index.php/buzz/viewBuzz</value>
      <webElementGuid>ad1ae82a-c5c0-473a-9276-c4e5928d32e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_buzz_viewBuzz</value>
      <webElementGuid>209845fb-4e0f-4ed0-aca2-b36c41a36219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>firstLevelMenu</value>
      <webElementGuid>b3009238-3dbc-4a67-9619-63b47674dbe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buzz</value>
      <webElementGuid>13ee4759-975b-406a-9b7b-eeae49014374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_buzz_viewBuzz&quot;)</value>
      <webElementGuid>791e1cd5-03f5-4f0b-9257-f23011974040</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu_buzz_viewBuzz']</value>
      <webElementGuid>4bf8e48b-e9d0-42b7-b174-cd8997e96257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mainMenuFirstLevelUnorderedList']/li[11]/a</value>
      <webElementGuid>3ae0b567-6221-4ae7-9fe4-52e02f78a35e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Access Records'])[1]/following::a[1]</value>
      <webElementGuid>a51eb8cf-4510-4694-89a2-75e562419a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Candidate Records'])[1]/following::a[2]</value>
      <webElementGuid>0d17eeba-cf61-4912-bf38-d53b5bb907ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purge Employee Records'])[1]/preceding::a[1]</value>
      <webElementGuid>a94ceab3-7335-4352-b32d-56b107da7935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/index.php/buzz/viewBuzz')]</value>
      <webElementGuid>691682ed-ec84-4d9e-be22-80207e7bbd4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]/a</value>
      <webElementGuid>987f7498-2fc9-4e96-9fcf-0781954011ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/index.php/buzz/viewBuzz' and @id = 'menu_buzz_viewBuzz' and (text() = 'Buzz' or . = 'Buzz')]</value>
      <webElementGuid>8d4600e9-8d1e-4a24-b19d-99580455b0ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
