<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_Recruitment</name>
   <tag></tag>
   <elementGuidId>9a0be58c-8af9-4b24-ba04-f70a1b687146</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_recruitment_viewRecruitmentModule']/b</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu_recruitment_viewRecruitmentModule > b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>fe9271eb-b5d1-4ce9-9c1b-850904876f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recruitment</value>
      <webElementGuid>f555c6f3-0cb3-41ca-9d79-dfee56be4c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_recruitment_viewRecruitmentModule&quot;)/b[1]</value>
      <webElementGuid>01b489f4-55fc-4b90-93a9-17eea61bf8c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='menu_recruitment_viewRecruitmentModule']/b</value>
      <webElementGuid>755d38de-81b7-47a7-80f8-4ceb7bdefffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Projects'])[1]/following::b[1]</value>
      <webElementGuid>4a6d9b9e-823c-452d-85b3-ed2902365d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customers'])[1]/following::b[1]</value>
      <webElementGuid>f45a1ed3-ef73-457b-8cf9-78f6aea225e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Candidates'])[1]/preceding::b[1]</value>
      <webElementGuid>3a2dfd1c-6171-4d41-a21d-1426f67d535f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vacancies'])[1]/preceding::b[1]</value>
      <webElementGuid>5c101432-b0ac-43fc-a6c3-528c724d939e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Recruitment']/parent::*</value>
      <webElementGuid>ae9e3645-94e2-46ee-8ebc-178480bd7678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/b</value>
      <webElementGuid>9db31102-d8a9-49de-8f13-4c1e3b869ce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'Recruitment' or . = 'Recruitment')]</value>
      <webElementGuid>c79e8eaa-63f8-44e6-8676-5c35c35d9acb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
