<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Add to Compare_replace-2x img-responsive</name>
   <tag></tag>
   <elementGuidId>d07372cb-f941-465a-96aa-6182cc95d84d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.ajax_block_product.col-xs-12.col-sm-6.col-md-4.last-item-of-tablet-line > div.product-container > div.left-block > div.product-image-container > a.product_img_link > img.replace-2x.img-responsive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='center_column']/ul/li[2]/div/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5305d4ee-2747-4c64-9082-27b92046b908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>replace-2x img-responsive</value>
      <webElementGuid>d822fc96-d7b9-4c6c-9908-e51ae01a40d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://automationpractice.com/img/p/1/0/10-home_default.jpg</value>
      <webElementGuid>38475304-24bb-4ed6-929f-d475565b504e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Printed Dress</value>
      <webElementGuid>9cf33b5a-417e-48fd-abd9-c3562491278b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Printed Dress</value>
      <webElementGuid>e197f1b8-4b3e-4a6c-82e7-1e1357011ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>fab3d902-f765-4bcf-a1d3-996ec17870e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>e92ab14c-e65c-4576-af34-bb93339fa8d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemprop</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>280d9329-d1f6-4f6a-9056-9b2fe043362f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;center_column&quot;)/ul[@class=&quot;product_list grid row&quot;]/li[@class=&quot;ajax_block_product col-xs-12 col-sm-6 col-md-4 last-item-of-tablet-line&quot;]/div[@class=&quot;product-container&quot;]/div[@class=&quot;left-block&quot;]/div[@class=&quot;product-image-container&quot;]/a[@class=&quot;product_img_link&quot;]/img[@class=&quot;replace-2x img-responsive&quot;]</value>
      <webElementGuid>ec9a1be9-2de4-4874-a423-63e38a9271be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='center_column']/ul/li[2]/div/div/div/a/img</value>
      <webElementGuid>1782a983-c8aa-4fdc-8828-0f6c020d79cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Printed Dress'])[2]</value>
      <webElementGuid>c474712e-4b6b-4ea5-8390-12fc069600ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div/a/img</value>
      <webElementGuid>033ad81f-efd5-404f-9532-2590ff169acb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://automationpractice.com/img/p/1/0/10-home_default.jpg' and @alt = 'Printed Dress' and @title = 'Printed Dress']</value>
      <webElementGuid>916bd9ba-2a08-4482-af13-64ca905cb3e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
